### PR TITLE
New website

### PR DESCRIPTION
**Pull request by jacobsanz97**
I'm just figuring out how GitHub branches work...But here should be the new version of the website.
I reckon almost everything is done as I Googled and used Lab Docs to fill in the info (other than some project descriptions, which I tried to find and couldn't).
Let me know if anything needs changing!

### CODE REVIEW

**Comment by emdupre** [comment]
Thanks, @jacobsanz97 !!

Do you have a build of this somewhere that we could demo in reviewing ? You should be able to build it directly on your repo, [see this guide](https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site).

**Comment by jacobsanz97** [comment]
> Thanks, @jacobsanz97 !!
> 
> Do you have a build of this somewhere that we could demo in reviewing ? You should be able to build it directly on your repo, [see this guide](https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site).

I have built it in my [repo](https://jacobsanz97.github.io/neurodatascience.github.io/) but the navigation doesn't work and the images don't load here due to the fact that I'm also using GitHub Pages to host my own personal page (so the reference links are pointing to the wrong places).
I can backup and delete my personal page for this demo, or maybe you could pull and serve it locally? Or is there another simpler way?

**Comment by emdupre** [comment]
Getting a local jekyll environment is finicky... my current one fails on this with the following error:

```
Liquid Exception: undefined method `valid_encoding?' for nil:NilClass in _includes/project-card.html, included in index.html
jekyll 3.1.6 | Error:  undefined method `valid_encoding?' for nil:NilClass
```

How about this. Let's update the destination branch for this PR (from `master` to `gh-pages`) and merge it. Then we can change where the site builds from and iterate as necessary. Since you're pulling over the main content, I can't imagine it will be a problem to update like this, but we'll have the other copy to fallback to if a problem arises.

**Comment by emdupre** [comment]
OK, I'll merge this now and we can iterate from there. Thanks again, @jacobsanz97 !!

**Comment by jacobsanz97** [comment]
Woo! Let me know if I need to do anything else. I'll update the remaining projects and stuff after I get them from people (or they can update them themselves).

**Pull request merged**
